export const actors = [
  {
    adult: false,
    gender: 1,
    id: 234352,
    known_for_department: "Acting",
    name: "Margot Robbie",
    popularity: 85.315,
    profile_path: "/euDPyqLnuwaWMHajcU3oZ9uZezR.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 18918,
    known_for_department: "Acting",
    name: "Dwayne Johnson",
    popularity: 44.349,
    profile_path: "/cgoy7t5Ve075naBPcewZrc08qGw.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 2231,
    known_for_department: "Acting",
    name: "Samuel L. Jackson",
    popularity: 26.306,
    profile_path: "/mXN4Gw9tZJVKrLJHde2IcUHmV3P.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 117642,
    known_for_department: "Acting",
    name: "Jason Momoa",
    popularity: 26.24,
    profile_path: "/6dEFBpZH8C8OijsynkSajQT99Pb.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 500,
    known_for: [
      {
        adult: false,
        backdrop_path: "/auZIuHEUec5tBTns3tCRXfayxZq.jpg",
        genre_ids: [28, 878],
        id: 137113,
        media_type: "movie",
        original_language: "en",
        original_title: "Edge of Tomorrow",
        overview:
          "В недалёком будущем раса инопланетян вторгается на Землю. Никакая армия в мире не может противостоять им. Майор Уильям Кейдж умирает в бою, но случается невозможное - он оказывается во временной петле. Раз за разом он попадает в один и тот же бой, сражается и умирает... снова и снова. И каждое повторяющееся сражение приближает его к разгадке того, как победить врага.",
        poster_path: "/z1TAt4eML51T3xUFyqBs5EaqRBY.jpg",
        release_date: "2014-05-27",
        title: "Грань будущего",
        video: false,
        vote_average: 7.6,
        vote_count: 10829,
      },
      {
        adult: false,
        backdrop_path: "/yvFtIWMvRS8PUbJOGpkSZk07CB3.jpg",
        genre_ids: [28, 878, 12, 9648],
        id: 75612,
        media_type: "movie",
        original_language: "en",
        original_title: "Oblivion",
        overview:
          "Можно ли скучать по месту, в котором никогда не был, мечтать о девушке, которую никогда не видел? Добро пожаловать в будущее! Мы больше не можем называть Землю своим домом. Мы выиграли войну, но не смогли сохранить планету…",
        poster_path: "/u8gzft5aJ2BPr6gQodjSz9MV8sg.jpg",
        release_date: "2013-04-10",
        title: "Обливион",
        video: false,
        vote_average: 6.6,
        vote_count: 8748,
      },
      {
        adult: false,
        backdrop_path: "/hqyjzDRCs1N5gEsh2gklzPdsEFD.jpg",
        genre_ids: [28, 53, 12],
        id: 56292,
        media_type: "movie",
        original_language: "en",
        original_title: "Mission: Impossible - Ghost Protocol",
        overview:
          "Специальный агент отряда «Миссия невыполнима» Итан Хант и его коллеги несправедливо обвинены в причастности к взрыву Кремля. Президент инициирует «Протокол Фантом», в результате которого спецподразделение ликвидировано, и Итан остается без какой-либо поддержки. Он намерен очистить свое доброе имя и предотвратить новую атаку, но делать это ему придется вместе с командой коллег, истинных мотивов которых он до конца не знает.",
        poster_path: "/neKiBzXzI6yuN8Fn8beoLcYASsE.jpg",
        release_date: "2011-12-07",
        title: "Миссия невыполнима: Протокол Фантом",
        video: false,
        vote_average: 7,
        vote_count: 7796,
      },
    ],
    known_for_department: "Acting",
    name: "Tom Cruise",
    popularity: 25.892,
    profile_path: "/8qBylBsQf4llkGrWR3qAsOtOU8O.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 17605,
    known_for: [
      {
        adult: false,
        backdrop_path: "/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg",
        genre_ids: [12, 28, 878],
        id: 299536,
        media_type: "movie",
        original_language: "en",
        original_title: "Avengers: Infinity War",
        overview:
          "Пока Мстители и их союзники продолжают защищать мир от различных опасностей, с которыми не смог бы справиться один супергерой, новая угроза возникает из космоса: Танос. Межгалактический тиран преследует цель собрать все шесть Камней Бесконечности — артефакты невероятной силы, с помощью которых можно менять реальность по своему желанию. Всё, с чем Мстители сталкивались ранее, вело к этому моменту — судьба Земли никогда ещё не была столь неопределённой.",
        poster_path: "/qIUFg6tzKeK5bUDguonWCAFceNB.jpg",
        release_date: "2018-04-25",
        title: "Мстители: Война бесконечности",
        video: false,
        vote_average: 8.3,
        vote_count: 22391,
      },
      {
        adult: false,
        backdrop_path: "/xnqust9Li4oxfhXD5kcPi3UC8i4.jpg",
        genre_ids: [28, 12, 878],
        id: 99861,
        media_type: "movie",
        original_language: "en",
        original_title: "Avengers: Age of Ultron",
        overview:
          "Человечество на грани уничтожения. На этот раз людям угрожает Альтрон — искусcтвенный интеллект, ранее созданый для того, чтобы защищать Землю от любых угроз. Однако, главной угрозой он посчитал человечество. Международная организация Щ. И. Т не способна справится с таким мощным врагом, и потому они вновь обращаются за помощью к Величайшим Героям Земли — Мстителям. Однако Альтрон слишком силен, и есть большая вероятность, что даже им не удастся остановить начало надвигающейся Эры Альтрона, где нет места для людей…",
        poster_path: "/6rANrpZe3g2PPeF1m3lQUK1ovpW.jpg",
        release_date: "2015-04-22",
        title: "Мстители: Эра Альтрона",
        video: false,
        vote_average: 7.3,
        vote_count: 18313,
      },
      {
        adult: false,
        backdrop_path: "/3SDoquTjagne0jWzdxEu31KFLmw.jpg",
        genre_ids: [12, 14, 28],
        id: 10195,
        media_type: "movie",
        original_language: "en",
        original_title: "Thor",
        overview:
          "Эпическое приключение происходит как на нашей планете Земля, так и в вымышленном королевстве богов Асгарде. В центре истории — Могучий Тор, сильный, но высокомерный воин, чьи безрассудные поступки возрождают древнюю войну в Асгарде. Тора отправляют в ссылку на Землю, лишают сил и заставляют жить среди обычных людей в качестве наказания. Тор узнает, сколько требуется сил, чтобы стать настоящим героем, когда самый опасный злодей его мира направляет темные силы поглотить Землю.",
        poster_path: "/i27DaxmuTzKZ8jgs7eoKQ8E03ny.jpg",
        release_date: "2011-04-21",
        title: "Тор",
        video: false,
        vote_average: 6.8,
        vote_count: 16860,
      },
    ],
    known_for_department: "Acting",
    name: "Idris Elba",
    popularity: 25.785,
    profile_path: "/be1bVF7qGX91a6c5WeRPs5pKXln.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 79127,
    known_for: [
      {
        backdrop_path: "/dqtpDD9Ro1uSdEOX8P1T6M3QdFI.jpg",
        first_air_date: "2006-02-03",
        genre_ids: [35],
        id: 2490,
        media_type: "tv",
        name: "Компьютерщики",
        origin_country: ["GB"],
        original_language: "en",
        original_name: "The IT Crowd",
        overview:
          "Действие сериала происходит в офисах «Reynholm Industries» — вымышленной британской корпорации, расположенной в центре Лондона. Сюжет строится вокруг проделок команды поддержки информационных технологий, состоящей из трёх человек и находящейся в грязном, запущенном подвале, сильно контрастирующим с блеском современной архитектуры и великолепными видами Лондона, доступных остальным подразделениям организации.",
        poster_path: "/1R550Xt4HpGCMr7HitsbFlRcAUS.jpg",
        vote_average: 8.1,
        vote_count: 786,
      },
      {
        backdrop_path: "/kC3jZ6RKnA7VUYQBnVFB5EbZtvu.jpg",
        first_air_date: "2015-06-14",
        genre_ids: [18, 9648, 10765],
        id: 62822,
        media_type: "tv",
        name: "Люди",
        origin_country: ["GB"],
        original_language: "en",
        original_name: "Humans",
        overview:
          "«Люди» — научно-фантастическая драма совместного производства американского канала AMC и британского Channel 4, в основу которой был положен шведский сериал «Настоящие люди» (Real Humans). Сильно приближенный к знакомой нам реальности проект повествует о классическом противостоянии людей и искусственного интеллекта со всеми вытекающими из этого проблемами. Сериал отличается серьезным подходом к на первый взгляд избитой теме использования роботов в повседневной жизни. Провокационные идеи, правдоподобный мир будущего, умело реализованные элементы фантастики, атмосферность и сильная актерская игра — вот главные движущие факторы телешоу. Любители качественной фантастики могут быть спокойны: Humans намеревается держать высочайшую планку качества, не спекулируя на хитроумных уловках.",
        poster_path: "/5aaHrLsZUbgpgNh4fzzFeiY4zq6.jpg",
        vote_average: 7.5,
        vote_count: 395,
      },
      {
        adult: false,
        backdrop_path: "/2bTtBL10fVvYBzugNMy0WV4r7pj.jpg",
        genre_ids: [18, 9648, 53],
        id: 35080,
        media_type: "movie",
        original_language: "en",
        original_title: "The Cat's Meow",
        overview:
          "В ноябре 1924 года произошло странное событие, шокировавшее знаменитую «фабрику грез». Во время круиза на яхте всемогущего медиа-магната Хёрста был убит знаменитый продюсер и режиссер Томас Инс.  Однако об этом не писала пресса, не было проведено расследование, и только невероятные слухи о тайном заговоре и паутине безумных страстей и беззастенчивой лжи, опутавшей неподражаемого Чарли Чаплина, легендарного Уильяма Хёрста, его очаровательную юную любовницу Мэрион Дэвис и несчастную жертву, помогли спустя много лет нарисовать картину загадочного происшествия, правда о котором умерла вместе с «золотой эпохой» сказочного Голливуда…",
        poster_path: "/zEVZa9EuApL5AQl2mE9NNAeCUix.jpg",
        release_date: "2001-08-03",
        title: "Смерть в Голливуде",
        video: false,
        vote_average: 6,
        vote_count: 61,
      },
    ],
    known_for_department: "Acting",
    name: "Claudia Harrison",
    popularity: 25.71,
    profile_path: "/dSK2BBupETZYcsO0DfP2OD1AMnT.jpg",
  },
  {
    adult: false,
    gender: 0,
    id: 41953,
    known_for: [
      {
        adult: false,
        genre_ids: [18],
        id: 161905,
        media_type: "movie",
        original_language: "en",
        original_title: "Testing the Limits",
        overview: "",
        poster_path: "/pnK24nc7EuYEmozCeIGXfKZdMIi.jpg",
        release_date: "1998-01-01",
        title: "Testing the Limits",
        video: false,
        vote_average: 5.1,
        vote_count: 11,
      },
      {
        adult: false,
        genre_ids: [18, 10749],
        id: 61192,
        media_type: "movie",
        original_language: "en",
        original_title: "Personals: College Girl Seeking...",
        overview: "",
        poster_path: "/gf1DkZulC46i4dLbjrR2CHZUyry.jpg",
        release_date: "2001-04-17",
        title: "Personals: College Girl Seeking...",
        video: false,
        vote_average: 6.5,
        vote_count: 4,
      },
      {
        adult: false,
        genre_ids: [18, 878, 10749],
        id: 137239,
        media_type: "movie",
        original_language: "en",
        original_title: "Virtual Encounters 2",
        overview: "",
        release_date: "1998-06-08",
        title: "Virtual Encounters 2",
        video: false,
        vote_average: 5.3,
        vote_count: 4,
      },
    ],
    known_for_department: "Acting",
    name: "Brandy Davis",
    popularity: 25.068,
    profile_path: null,
  },
  {
    adult: false,
    gender: 1,
    id: 1084910,
    known_for: [
      {
        adult: false,
        backdrop_path: "/oLPxM7Zx2tsilktqrxCUz5M99cc.jpg",
        genre_ids: [12, 28, 18, 36],
        id: 127533,
        media_type: "movie",
        original_language: "ja",
        original_title: "るろうに剣心",
        overview:
          "Бывший легендарный убийца Кэнсин Химура стал скитальцем самураем, предлагающим помощь и защиту нуждающимся, чтобы искупить свои прошлые поступки. Во время своих скитаний Кэнсин столкнется с Каору Камией. Ее отец открыл школу кэндо в Токио и Каору работает там инструктором. Отношения Кэнсина и Каору начинают развиваться, но Кэнсина по-прежнему преследует его ужасное прошлое",
        poster_path: "/atUOYrbF8vdc45AU0lPnd5aNdKd.jpg",
        release_date: "2012-08-25",
        title: "Бродяга Кэнсин",
        video: false,
        vote_average: 7.6,
        vote_count: 492,
      },
      {
        adult: false,
        backdrop_path: "/q3jiq1PRpOGnRScbj3cur7RkZYv.jpg",
        genre_ids: [28, 12, 18, 14],
        id: 221731,
        media_type: "movie",
        original_language: "ja",
        original_title: "るろうに剣心 京都大火編",
        overview:
          "Продолжение истории о похождениях Кэнсина Химуры, некогда легендарного убийцы, вступившего на путь искупления. На этот раз Кэнсин вступает в противостояние с самим Шишио Макото, злодеем, вознамерившимся свергнуть правительство Мэйдзи и подчинить себе всю Японию. Судьба страны висит на волоске, и скиталец-самурай Химура вновь берет в руки меч, к которому он поклялся никогда не прикасаться снова.",
        poster_path: "/3Z9WUWk8aBey9WALtmyZVlloaAN.jpg",
        release_date: "2014-08-01",
        title: "Бродяга Кэнсин: Великий киотский пожар",
        video: false,
        vote_average: 7.7,
        vote_count: 346,
      },
      {
        adult: false,
        backdrop_path: "/4UXfZjqt0C5kHTROotrsnfDYCh.jpg",
        genre_ids: [28, 12, 18, 14],
        id: 221732,
        media_type: "movie",
        original_language: "ja",
        original_title: "るろうに剣心　伝説の最期編",
        overview:
          "Фильм повествует о наемном убийце, который решил стать на праведный путь и искупить свои грехи, учиненные в прошлом. Он дал себе обещание, что больше никогда не убьет человека, а меч будет применять только в благородных целях — для защиты нуждающихся. Но жизнь складывается таким образом, что Кэнсина Химуру снова должен обнажить свой меч.  В Киото появляется жестокий и расчетливый убийца по имени Шишио Макато, который приехал для того, чтобы свергнуть действующую власть и прибрать ее в свои руки. Никто, кроме нашего героя, не сможет защитить правительство Японии, которое сейчас так сильно нуждается в помощи. Химура — единственный, кто может противостоять Макато. Тем более, что ему всегда готовы помочь верные друзья. Битва между двумя врагами станет решающей, ведь только после нее можно будет понять, кто же настоящая легенда.",
        poster_path: "/ijV6arEmM8nZwVUJoYY8tAIRhJg.jpg",
        release_date: "2014-09-13",
        title: "Бродяга Кэнсин: Последняя легенда",
        video: false,
        vote_average: 7.8,
        vote_count: 275,
      },
    ],
    known_for_department: "Acting",
    name: "Emi Takei",
    popularity: 24.699,
    profile_path: "/aGg47CnHc1wgIOtwt4rbQWbWuDg.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 91606,
    known_for: [
      {
        adult: false,
        backdrop_path: "/nNmJRkg8wWnRmzQDe2FwKbPIsJV.jpg",
        genre_ids: [878, 28, 12],
        id: 24428,
        media_type: "movie",
        original_language: "en",
        original_title: "The Avengers",
        overview:
          "Локи, сводный брат Тора, возвращается, и в этот раз он не один. Земля на грани порабощения, и только лучшие из лучших могут спасти человечество.  Ник Фьюри, глава международной организации Щ.И.Т., собирает выдающихся поборников справедливости и добра, чтобы отразить атаку. Под предводительством Капитана Америки Железный Человек, Тор, Невероятный Халк, Соколиный глаз и Чёрная Вдова вступают в войну с захватчиком.",
        poster_path: "/ztkYgL0zHJLnEPY5VabK9OlmXxx.jpg",
        release_date: "2012-04-25",
        title: "Мстители",
        video: false,
        vote_average: 7.7,
        vote_count: 25157,
      },
      {
        adult: false,
        backdrop_path: "/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg",
        genre_ids: [12, 28, 878],
        id: 299536,
        media_type: "movie",
        original_language: "en",
        original_title: "Avengers: Infinity War",
        overview:
          "Пока Мстители и их союзники продолжают защищать мир от различных опасностей, с которыми не смог бы справиться один супергерой, новая угроза возникает из космоса: Танос. Межгалактический тиран преследует цель собрать все шесть Камней Бесконечности — артефакты невероятной силы, с помощью которых можно менять реальность по своему желанию. Всё, с чем Мстители сталкивались ранее, вело к этому моменту — судьба Земли никогда ещё не была столь неопределённой.",
        poster_path: "/qIUFg6tzKeK5bUDguonWCAFceNB.jpg",
        release_date: "2018-04-25",
        title: "Мстители: Война бесконечности",
        video: false,
        vote_average: 8.3,
        vote_count: 22391,
      },
      {
        adult: false,
        backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
        genre_ids: [12, 878, 28],
        id: 299534,
        media_type: "movie",
        original_language: "en",
        original_title: "Avengers: Endgame",
        overview:
          'После разрушительных событий в "Мстители: Войны бесконечности", вселенная лежит в руинах. Оставшиеся в живых участники команды Мстителей снова объединяются в попытке восстановить баланс во вселенной.',
        poster_path: "/97Vh0jjRm1iND3kui7frYLU3Ajs.jpg",
        release_date: "2019-04-24",
        title: "Мстители: Финал",
        video: false,
        vote_average: 8.3,
        vote_count: 18775,
      },
    ],
    known_for_department: "Acting",
    name: "Tom Hiddleston",
    popularity: 24.656,
    profile_path: "/mclHxMm8aPlCPKptP67257F5GPo.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 48,
    known_for: [
      {
        adult: false,
        backdrop_path: "/vRQnzOn4HjIMX4LBq9nHhFXbsSu.jpg",
        genre_ids: [12, 14, 28],
        id: 120,
        media_type: "movie",
        original_language: "en",
        original_title: "The Lord of the Rings: The Fellowship of the Ring",
        overview:
          "Сказания о Средиземье — это хроника Великой войны за Кольцо, войны, длившейся не одну тысячу лет. Тот, кто владел Кольцом, получал власть над всеми живыми тварями, но был обязан служить злу. Тихая деревня, где живут хоббиты. Волшебник Гэндальф, придя на 111-й день рождения к своему старому другу Бильбо Бэггинсу, начинает вести разговор о кольце, которое Бильбо нашёл много лет назад. Это кольцо принадлежало когда-то тёмному властителю Средиземья Саурону, и оно даёт большую власть своему обладателю. Теперь Саурон хочет вернуть себе власть над Средиземьем. Бильбо отдаёт найденное кольцо своему племяннику Фродо, который пытается научиться справляться с тем страшным могуществом, которое даёт ему кольцо…",
        poster_path: "/xGeAWst9lwoJj7ldCWerBjAyUNk.jpg",
        release_date: "2001-12-18",
        title: "Властелин колец: Братство кольца",
        video: false,
        vote_average: 8.4,
        vote_count: 19493,
      },
      {
        adult: false,
        backdrop_path: "/pm0RiwNpSja8gR0BTWpxo5a9Bbl.jpg",
        genre_ids: [12, 14, 28],
        id: 122,
        media_type: "movie",
        original_language: "en",
        original_title: "The Lord of the Rings: The Return of the King",
        overview:
          "Последняя часть трилогии о Кольце Всевластия и о героях, взявших на себя бремя спасения Средиземья. Повелитель сил Тьмы Саурон направляет свои бесчисленные рати под стены Минас-Тирита, крепости Последней Надежды. Он предвкушает близкую победу, но именно это и мешает ему заметить две крохотные фигурки — хоббитов, приближающихся к Роковой Горе, где им предстоит уничтожить Кольцо Всевластия. Улыбнется ли им счастье?",
        poster_path: "/t5CNKKanYVzrcDmute3NWKXdfhC.jpg",
        release_date: "2003-12-01",
        title: "Властелин колец: Возвращение Короля",
        video: false,
        vote_average: 8.5,
        vote_count: 18054,
      },
      {
        adult: false,
        backdrop_path: "/kWYfW2Re0rUDE6IHhy4CRuKWeFr.jpg",
        genre_ids: [12, 14, 28],
        id: 121,
        media_type: "movie",
        original_language: "en",
        original_title: "The Lord of the Rings: The Two Towers",
        overview:
          "Братство распалось, но Кольцо Всевластья должно быть уничтожено. Фродо и Сэм вынуждены доверить свои жизни Голлуму, который взялся провести их к вратам Мордора. Громадная Армия Сарумана приближается: члены братства и их союзники готовы принять бой. Битва за Средиземье продолжается.",
        poster_path: "/3xaAYgBUJcJ6yievC5Ma3pMJkMv.jpg",
        release_date: "2002-12-18",
        title: "Властелин колец: Две крепости",
        video: false,
        vote_average: 8.3,
        vote_count: 16851,
      },
    ],
    known_for_department: "Acting",
    name: "Sean Bean",
    popularity: 24.231,
    profile_path: "/kTjiABk3TJ3yI0Cto5RsvyT6V3o.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 1784612,
    known_for: [
      {
        adult: false,
        backdrop_path: "/jlGmlFOcfo8n5tURmhC7YVd4Iyy.jpg",
        genre_ids: [28, 12, 35, 878],
        id: 436969,
        media_type: "movie",
        original_language: "en",
        original_title: "The Suicide Squad",
        overview:
          "Есть на земле одно гнилое место, откуда мечтают свалить даже самые отъявленные злодеи. Тюрьма Белль Рив — для преступников со сверхспособностями. Она же — ад. Она же — база рекрутов для суперсекретного проекта «Отряд самоубийц».",
        poster_path: "/b08rGloeZSuJyx6wDX2Q8plC6ID.jpg",
        release_date: "2021-07-28",
        title: "Отряд самоубийц: Миссия навылет",
        video: false,
        vote_average: 8.1,
        vote_count: 1424,
      },
      {
        backdrop_path: "/lQFzeBxQBSyHwtaGcsOd9eKnELr.jpg",
        first_air_date: "2017-09-24",
        genre_ids: [18, 10766],
        id: 73951,
        media_type: "tv",
        name: "A Herdeira",
        origin_country: ["PT"],
        original_language: "pt",
        original_name: "A Herdeira",
        overview: "",
        poster_path: "/Acf1EEhOZwDNB0IuuICwyIDfYqF.jpg",
        vote_average: 3.9,
        vote_count: 40,
      },
      {
        backdrop_path: null,
        first_air_date: "2017-01-08",
        genre_ids: [18, 10766],
        id: 69692,
        media_type: "tv",
        name: "Зеленое золото",
        origin_country: ["PT"],
        original_language: "pt",
        original_name: "Ouro Verde",
        overview: "",
        poster_path: "/2hJN6OVo8FL0C9mXl3DJ3uM96Sj.jpg",
        vote_average: 4.6,
        vote_count: 13,
      },
    ],
    known_for_department: "Acting",
    name: "Daniela Melchior",
    popularity: 23.715,
    profile_path: "/ieINP7YlragZ999aU0zfuve1lM2.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 92404,
    known_for: [
      {
        adult: false,
        backdrop_path: "/dpoIQ9MN54cxuLZxDABEUOSFGY3.jpg",
        genre_ids: [28, 12, 14],
        id: 297761,
        media_type: "movie",
        original_language: "en",
        original_title: "Suicide Squad",
        overview:
          "Правительство решает дать команде суперзлодеев шанс на искупление. Подвох в том, что их отправляют на миссию, где они, вероятнее всего, погибнут...",
        poster_path: "/qLISDJS1AZoKffgMaVuma0ncuXE.jpg",
        release_date: "2016-08-03",
        title: "Отряд самоубийц",
        video: false,
        vote_average: 5.9,
        vote_count: 17677,
      },
      {
        adult: false,
        backdrop_path: "/dNFbrnF0mIBm0rClbfEFWTtsgMP.jpg",
        genre_ids: [53, 80, 9648, 18],
        id: 65754,
        media_type: "movie",
        original_language: "en",
        original_title: "The Girl with the Dragon Tattoo",
        overview:
          "Сорок лет назад Харриет Вангер бесследно пропала на острове, принадлежащем могущественному клану Вангер. Ее тело так и не было найдено, но ее дядя убежден, что это убийство и что убийца является членом его собственной, тесно сплоченной и неблагополучной семьи. Он нанимает опального журналиста Микаэля Блумквиста и татуированную хакершу Лисбет Саландер для проведения расследования.",
        poster_path: "/x0xAyBpN7ND0N5B0D30xbxscL4o.jpg",
        release_date: "2011-12-14",
        title: "Девушка с татуировкой дракона",
        video: false,
        vote_average: 7.3,
        vote_count: 5362,
      },
      {
        adult: false,
        backdrop_path: "/hTDAWiohFTwJaKNcCNlsKs64bip.jpg",
        genre_ids: [878, 28],
        id: 97020,
        media_type: "movie",
        original_language: "en",
        original_title: "RoboCop",
        overview:
          "2028 год. Международный конгломерат ОмниКорп лидирует в производстве робототехники. Благодаря разработкам компании Америка успешно побеждает в войнах по всему миру. Но теперь пришло время применить технологию на американской земле. Алекс Мерфи - любящий муж, отец и отличный полицейский, оберегающий порядок в Детройте, получает на службе смертельные ранения. Специалисты ОмниКорпа, используя новейшие разработки, сохраняют ему жизнь. Алекс возвращается на службу в родной город не только с новыми сверхспособностями, но и с проблемами, с которыми не сталкивался ни один живой человек.",
        poster_path: "/kFd56dy1nj9FLTk105ggvydZgf1.jpg",
        release_date: "2014-01-30",
        title: "РобоКоп",
        video: false,
        vote_average: 5.8,
        vote_count: 4402,
      },
    ],
    known_for_department: "Acting",
    name: "Joel Kinnaman",
    popularity: 22.875,
    profile_path: "/c4TTWy1WntzDxpgIe8kbODjWOfD.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 58369,
    known_for: [
      {
        backdrop_path: "/wvdWb5kTQipdMDqCclC6Y3zr4j3.jpg",
        first_air_date: "2010-10-31",
        genre_ids: [10759, 18, 10765],
        id: 1402,
        media_type: "tv",
        name: "Ходячие мертвецы",
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Walking Dead",
        overview:
          "Сериал рассказывает историю жизни семьи шерифа после того, как «зомби» — эпидемия апокалиптических масштабов захлестнула земной шар. Шериф Рик Граймс путешествует со своей семьей и небольшой группой выживших в поисках безопасного места для жизни. Но постоянный страх смерти каждый день приносит тяжелые потери, заставляя героев почувствовать глубины человеческой жестокости. Рик пытается спасти свою семью, и открывает для себя, что всепоглощающий страх тех, кто выжил, может быть опаснее бессмысленных мертвецов, бродящих по земле.",
        poster_path: "/nRqzUMMBqw0sa5l8msinhDVP1BI.jpg",
        vote_average: 8.1,
        vote_count: 11268,
      },
      {
        backdrop_path: "/rNyOeC4uh0YMjZwtrLPFGyVIvyI.jpg",
        first_air_date: "2011-10-05",
        genre_ids: [18, 9648, 10765],
        id: 1413,
        media_type: "tv",
        name: "Американская история ужасов",
        origin_country: ["US"],
        original_language: "en",
        original_name: "American Horror Story",
        overview:
          "Первый сезон сериала сосредоточен на семействе Хармонов, которые переезжают из Бостона в Лос-Анджелес, чтобы начать новую жизнь, и поселяются в старинном отреставрированном особняке, не представляя, что его предыдущие жильцы так и не нашли покоя после смерти.\n\nВторой сезон рассказывает совершенно другую историю — действие разворачивается вокруг журналистки, которая приехала в психбольницу для душевнобольных преступников в надежде отснять репортаж о новоприбывшем маньяке «Кровавый лик», беспощадно убивавшем случайных женщин.\n\nВ третьем сезоне речь идет о шабаше ведьм, замаскированном под элитный пансион для «одаренных» девушек, который пытается защитить последних представительниц этого вида от вымирания.\n\nСюжет четвёртого сезона вращается вокруг одного из последних «Цирков уродов» в 1950-х годах.\n\nСобытия пятого сезона происходят в большом позабытом многими отеле в центральной части Лос-Анджелеса. Этот отель скрывает в своих стенах множество секретов.\n\nШестой сезон повествует о паре из Калифорнии, переезжающей в новый дом, в котором паранормальные явления начинают их преследовать.\n\nСедьмой сезон рассказывает о президентских выборах в США 2016 года.\n\nВ восьмом сезоне происходит апокалипсис. Несколько стран запустили ядерные ракеты, уничтожившие большую часть населения Земли. Избранным счастливчикам удалось укрыться в бункере.",
        poster_path: "/zEZIhMx3DTVXCV9ap7BevRX40SN.jpg",
        vote_average: 8.1,
        vote_count: 3802,
      },
      {
        backdrop_path: "/jbTqU6BJMufoMnPSlO4ThrcXs3Y.jpg",
        first_air_date: "1999-01-31",
        genre_ids: [16, 35],
        id: 1434,
        media_type: "tv",
        name: "Гриффины",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Family Guy",
        overview:
          "Типичная американская семья, члены которой способны разбить все возможные стереотипы. А говорящая собака с сигаретой и сухим мартини… А грудной малыш, мечтающий поработить весь мир… Разве это отклонение? Это катарсис в каждом эпизоде!",
        poster_path: "/seS4Uv5EvezwCS4aVfiBcvB4q4y.jpg",
        vote_average: 7,
        vote_count: 2878,
      },
    ],
    known_for_department: "Acting",
    name: "Alexandra Breckenridge",
    popularity: 22.515,
    profile_path: "/7HQAXqAELDwzZzxpmp1ZSb4yM5V.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 1367122,
    known_for: [
      {
        backdrop_path: "/yGNnjoIGOdQy3douq60tULY8teK.jpg",
        first_air_date: "2016-10-02",
        genre_ids: [10765, 37],
        id: 63247,
        media_type: "tv",
        name: "Мир Дикого Запада",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Westworld",
        overview:
          "В центре внимания сериала - небольшой парк развлечений, который специализируется на показе крутых гаджетов, роботов и прочей техники, которая призвана помогать человечеству. В этом заведении андроиды работают как рабы людей, пытаясь сделать все возможное, чтобы посетителям было комфортно. Однако однажды в их программе случается серьезный сбой, который делает из механических существ настоящих опасных убийц, способных навести хаос на всей планете. Что же теперь делать? Неужели начинается апокалипсис?",
        poster_path: "/j6fldQaouy30RJRfKbp4GRCQfle.jpg",
        vote_average: 8.1,
        vote_count: 3674,
      },
      {
        backdrop_path: "/ypLoTftyF5EpGBxJas4PThIdiU4.jpg",
        first_air_date: "2010-06-08",
        genre_ids: [18, 9648],
        id: 31917,
        media_type: "tv",
        name: "Милые обманщицы",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Pretty Little Liars",
        overview:
          "Сериал рассказывает о четырёх девушках — Спенсер, Ханне, Арии и Эмили, дружба которых прекратилась после исчезновения их общей лучшей подруги Элисон. Спустя год после её исчезновения, девушки начинают получать загадочные сообщения от анонима «A», который знает все их секреты — включая те, которые знала только Элисон — и угрожает их раскрытием. Но Элисон мертва. Кто же отправляет эти сообщения?",
        poster_path: "/frB4pyzEnYnO3F67iYPGZGEpEbr.jpg",
        vote_average: 8,
        vote_count: 1874,
      },
      {
        backdrop_path: "/jTiQAusGG4dVLSb1WHme9I9R4NN.jpg",
        first_air_date: "2013-09-17",
        genre_ids: [35, 80],
        id: 48891,
        media_type: "tv",
        name: "Бруклин 9-9",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Brooklyn Nine-Nine",
        overview:
          "История о том, что происходит, когда у детектива, не воспринимающего ничего серьезно, появляется новый руководитель, который хочет, чтобы он рос и с уважением относился к своей должности.",
        poster_path: "/5369PTB3hOUqcKEuJNFRMBZ2IDZ.jpg",
        vote_average: 8.2,
        vote_count: 1779,
      },
    ],
    known_for_department: "Acting",
    name: "Biff Wiff",
    popularity: 22.403,
    profile_path: "/3POiKfk91QSHTt176vnGdrtqudx.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 25837,
    known_for: [
      {
        adult: false,
        backdrop_path: "/uMZNQNKDVfvzw77TGc9brbZ8LiS.jpg",
        genre_ids: [35, 10749, 18],
        id: 508,
        media_type: "movie",
        original_language: "en",
        original_title: "Love Actually",
        overview:
          "Любовь незабываемая и недосягаемая, вызывающая сожаление и экстатическая, неожиданная и нежеланная, неудобная и необъяснимая, неизящная и неравная. Любовь поистине правит всеми вокруг. От премьер-министра, мгновенно влюбившегося в сотрудницу своего аппарата, — до писателя, сбежавшего на юг Франции, чтобы склеить свое разбитое сердце… От замужней женщины, подозревающей, что ее муж отдаляется от нее, — до женщины, только что вступившей в брак и почувствовавшей холодность лучшего друга своего мужа… От тинейджера, пытающегося завоевать внимание самой неприступной девочки в школе, — до овдовевшего отчима, пытающегося установить контакт с сыном, которого, как вдруг выясняется, он почти не знает… От страдающей из-за безнадежной любви юной американки, решившей не упустить своего шанса с сослуживцем, — до стареющего рок-певца, ставшего жертвой внезапно накатившего чувства… Любовь вносит хаос в жизнь каждого из них, но не случайно пути-дороги лондонцев сталкиваются в канун Рождества…",
        poster_path: "/bvgazyuurl8il9nYsXMU7aulWGL.jpg",
        release_date: "2003-09-07",
        title: "Реальная любовь",
        video: false,
        vote_average: 7.1,
        vote_count: 5069,
      },
      {
        backdrop_path: "/jbTqU6BJMufoMnPSlO4ThrcXs3Y.jpg",
        first_air_date: "1999-01-31",
        genre_ids: [16, 35],
        id: 1434,
        media_type: "tv",
        name: "Гриффины",
        origin_country: ["US"],
        original_language: "en",
        original_name: "Family Guy",
        overview:
          "Типичная американская семья, члены которой способны разбить все возможные стереотипы. А говорящая собака с сигаретой и сухим мартини… А грудной малыш, мечтающий поработить весь мир… Разве это отклонение? Это катарсис в каждом эпизоде!",
        poster_path: "/seS4Uv5EvezwCS4aVfiBcvB4q4y.jpg",
        vote_average: 7,
        vote_count: 2867,
      },
      {
        adult: false,
        backdrop_path: "/8RHLvjNnJCrp3dEIQpVqLHxf6UC.jpg",
        genre_ids: [35, 10749],
        id: 10591,
        media_type: "movie",
        original_language: "en",
        original_title: "The Girl Next Door",
        overview:
          "Старшеклассник Меттью, мечтая о карьере политика, между тем обнаруживает, что у него появилась новая соседка, неотразимая 19-летняя блондинка Дениэль. Цветочно-конфетная стадия пролетает мимолетно, и вот уже ослепленной любовью Меттью уверен, что он нашел женщину всей своей жизни. Каково же было его изумление, когда он вместе со всем городом узнаёт, что она — бывшая порнозвезда. И чтобы удержать ее, ему теперь придется рискнуть креслом сенатора и пройти испытание, к которому он не был готов…",
        poster_path: "/qS7lualKyUKOxDntuddgSOxAGBT.jpg",
        release_date: "2004-04-09",
        title: "Соседка",
        video: false,
        vote_average: 6.7,
        vote_count: 2445,
      },
    ],
    known_for_department: "Acting",
    name: "Elisha Cuthbert",
    popularity: 22.223,
    profile_path: "/jyo887Q2c3wgME6VqY92BvhENzb.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 3896,
    known_for: [
      {
        adult: false,
        backdrop_path: "/cKPfiu9IcCW0fMdKdQBXe3PRtTZ.jpg",
        genre_ids: [28, 80, 18, 53],
        id: 49026,
        media_type: "movie",
        original_language: "en",
        original_title: "The Dark Knight Rises",
        overview:
          "Восемь лет назад Бэтмен растворился в ночи, превратившись из героя в беглеца. Приняв на себя вину за смерть прокурора Харви Дента, Тёмный рыцарь пожертвовал всем. Вместе с комиссаром Гордоном они решили, что так будет лучше для всех. Пока преступность была раздавлена антикриминальным актом Дента, ложь действовала.\r Но с появлением хитрой воровки с загадочным прошлым всё меняется. Тем не менее, ещё опаснее становится появление террориста Бэйна, чьё лицо закрыто маской. Он разворачивает в Готэме чудовищную деятельность, вынуждая Брюса Уэйна выйти из импровизированного изгнания. Однако даже надев свой костюм, Бэтмен может проиграть Бэйну.",
        poster_path: "/ws4Hj54pdDsk2DdIEPDwZU8z5KT.jpg",
        release_date: "2012-07-16",
        title: "Тёмный рыцарь: Возрождение легенды",
        video: false,
        vote_average: 7.8,
        vote_count: 18102,
      },
      {
        adult: false,
        backdrop_path: "/lh5lbisD4oDbEKgUxoRaZU8HVrk.jpg",
        genre_ids: [28, 80, 18],
        id: 272,
        media_type: "movie",
        original_language: "en",
        original_title: "Batman Begins",
        overview:
          "Это иной Бэтмэн. Это новое начало. История о происхождении легенды Брюса Уэйна, юного наследника огромного состояния, потерявшего своих родителей. Покинув родной Готэм, он отправляется в путешествие по миру. Многочисленные преграды и лишения закаляют его характер, а мудрый наставник помогает вновь обрести смысл жизни. Легендарный герой, защитник слабых, борец с несправедливостью преображается у тебя на глазах. Вернувшись в Готэм, Бэтмэн становится единственной преградой на пути у сил зла, готовых ввергнуть город во мрак беззакония.",
        poster_path: "/3oOBjD1LZCjfrLPPL49xP9fFgeR.jpg",
        release_date: "2005-06-10",
        title: "Бэтмен: Начало",
        video: false,
        vote_average: 7.7,
        vote_count: 16410,
      },
      {
        adult: false,
        backdrop_path: "/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg",
        genre_ids: [18, 36, 10752],
        id: 424,
        media_type: "movie",
        original_language: "en",
        original_title: "Schindler's List",
        overview:
          "Лента рассказывает реальную историю загадочного Оскара Шиндлера, члена нацистской партии, преуспевающего фабриканта, спасшего во время Второй мировой войны более тысячи ста евреев. Это триумф одного человека, не похожего на других, и драма тех, кто, благодаря ему, выжил в ужасный период человеческой истории.",
        poster_path: "/4K8fGGcJP2EoGDucILnaJcOJhZl.jpg",
        release_date: "1993-11-30",
        title: "Список Шиндлера",
        video: false,
        vote_average: 8.6,
        vote_count: 11622,
      },
    ],
    known_for_department: "Acting",
    name: "Liam Neeson",
    popularity: 22.128,
    profile_path: "/bboldwqSC6tdw2iL6631c98l2Mn.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 16483,
    known_for: [
      {
        adult: false,
        backdrop_path: "/aJn9XeesqsrSLKcHfHP4u5985hn.jpg",
        genre_ids: [12, 28, 878, 35],
        id: 283995,
        media_type: "movie",
        original_language: "en",
        original_title: "Guardians of the Galaxy Vol. 2",
        overview:
          "Все в сборе: землянин Питер Квилл (Звездный Лорд), молчаливый громила Дракс, зеленокожая наемница Гамора, живое дерево Грут и говорящий енот. Герои не изменяют себе и с завидной регулярностью продолжают попадать в немыслимые ситуации, выпутываясь из них почти без ущерба (а иногда даже с пользой) для окружающих. На этот раз им предстоит раскрыть одну из самых главных тайн во всей Галактике: кто же на самом деле отец Питера Квилла?",
        poster_path: "/miAFwzWPkv7l8VPwgH2sV5oQQKx.jpg",
        release_date: "2017-04-19",
        title: "Стражи Галактики. Часть 2",
        video: false,
        vote_average: 7.6,
        vote_count: 16945,
      },
      {
        adult: false,
        backdrop_path: "/iEVZScwA2vy8BlVOFBBCfbU6XxB.jpg",
        genre_ids: [28, 12, 35, 878],
        id: 607,
        media_type: "movie",
        original_language: "en",
        original_title: "Men in Black",
        overview:
          "Они — самый большой секрет Земли. Они работают на неофициальное правительственное агентство, регулирующее деятельность инопланетян на Земле.Они — это лучшая, последняя и единственная линия защиты Земли от отбросов вселенной. Их работа секретна, их оружие совершенно, им нет равных, они не оставляют следов. Они — это Люди в черном.",
        poster_path: "/jCYu09SiyvJirlw0732HiK4XL0y.jpg",
        release_date: "1997-07-02",
        title: "Люди в чёрном",
        video: false,
        vote_average: 7.1,
        vote_count: 10876,
      },
      {
        adult: false,
        backdrop_path: "/gDRlw7GoA0OoLvijXNCTTdtAtNX.jpg",
        genre_ids: [53, 12, 28],
        id: 27578,
        media_type: "movie",
        original_language: "en",
        original_title: "The Expendables",
        overview:
          "США посылает в Корзу, — одну из стран Южной Америки, пять наемников для уничтожения местного диктатора. При этом, никто не заботится о том, что они должны выжить: их посылают на верную гибель, используя, как пушечное мясо…",
        poster_path: "/kx6qXzlYwM6lYi8PvU3XhBcmPDq.jpg",
        release_date: "2010-08-03",
        title: "Неудержимые",
        video: false,
        vote_average: 6.2,
        vote_count: 6055,
      },
    ],
    known_for_department: "Acting",
    name: "Sylvester Stallone",
    popularity: 22.012,
    profile_path: "/qDRGPAcQoW8Wuig9bvoLpHwf1gU.jpg",
  },
  {
    adult: false,
    gender: 1,
    id: 1016071,
    known_for: [
      {
        adult: false,
        backdrop_path: "/eqimWwbi9Og2XM3Y8Z2fK69j8gL.jpg",
        genre_ids: [18, 10749],
        id: 292431,
        media_type: "movie",
        original_language: "en",
        original_title: "Love",
        overview:
          "Любовь вне добра и зла. Любовь — это генетическая потребность. Это дар и проклятие. Любовь — это болезнь, наркотик. Это потеря и обретение себя. Любовь — это самое прекрасное и самое ужасное в нашей жизни. Любовь — это переплетение душ и соединение тел. «Любовь» — это возбуждающая сексуальная мелодрама о парне, девушке и еще одной девушке, которые постигают все радости секса.",
        poster_path: "/t9IR4jY9EJmh3WTvJ4hd6F8bWpW.jpg",
        release_date: "2015-07-06",
        title: "Любовь",
        video: false,
        vote_average: 6.4,
        vote_count: 1710,
      },
      {
        adult: false,
        backdrop_path: "/q0eXltiQKRqD3qMdN3OC55O06Dy.jpg",
        genre_ids: [18, 10749],
        id: 86331,
        media_type: "movie",
        original_language: "fr",
        original_title: "Q",
        overview:
          "Когда судьба приводит людей на грань отчаяния, единственным способом вновь ощутить вкус жизни может стать нежданный аттракцион грандиозных чувственных наслаждений, которые способна дарить каждому новому знакомому очаровательная Сесиль. Попадая к юной красотке в сладкий плен удовольствий, любой теряет голову; все прочее перестает иметь для него значение, кроме одного — секс, секс, секс…",
        poster_path: "/tSvNQLzY3tGSoDDTbPto8waHwnf.jpg",
        release_date: "2011-09-14",
        title: "Q: Загадка женщины",
        video: false,
        vote_average: 5,
        vote_count: 280,
      },
      {
        adult: false,
        backdrop_path: "/mSLDuAlfpaSrpE3LvNwWDgMQiK2.jpg",
        genre_ids: [18],
        id: 78363,
        media_type: "movie",
        original_language: "fr",
        original_title: "My Little Princess",
        overview:
          "11-летнюю Виолетту не спутать со сверстницами - не только потому, что пышные золотые волосы девочки видны за версту. Виолетта - ребёнок-звезда, героиня эстетских фотографий, сделанных блудной богемной мамой, превратившей свою дочь в объект эротического вожделения коллекционеров и пристального внимания социальных служб, гостью салонов и школьную парию.",
        poster_path: "/dl1uTSs5bksKkKwHupKroIc9LMy.jpg",
        release_date: "2011-06-29",
        title: "Моя маленькая принцесса",
        video: false,
        vote_average: 6.7,
        vote_count: 62,
      },
    ],
    known_for_department: "Acting",
    name: "Déborah Révy",
    popularity: 21.832,
    profile_path: "/a3EmfvlSIcRhIwFm6nFLWCnIuFi.jpg",
  },
  {
    adult: false,
    gender: 2,
    id: 22226,
    known_for: [
      {
        adult: false,
        backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
        genre_ids: [12, 878, 28],
        id: 299534,
        media_type: "movie",
        original_language: "en",
        original_title: "Avengers: Endgame",
        overview:
          'После разрушительных событий в "Мстители: Войны бесконечности", вселенная лежит в руинах. Оставшиеся в живых участники команды Мстителей снова объединяются в попытке восстановить баланс во вселенной.',
        poster_path: "/97Vh0jjRm1iND3kui7frYLU3Ajs.jpg",
        release_date: "2019-04-24",
        title: "Мстители: Финал",
        video: false,
        vote_average: 8.3,
        vote_count: 18775,
      },
      {
        adult: false,
        backdrop_path: "/kvRT3GwcnqGHzPjXIVrVPhUix7Z.jpg",
        genre_ids: [12, 28, 878],
        id: 271110,
        media_type: "movie",
        original_language: "en",
        original_title: "Captain America: Civil War",
        overview:
          "Мстители под руководством Капитана Америки оказываются участниками разрушительного инцидента, имеющего международный масштаб. Эти события заставляют правительство задуматься над тем, чтобы начать регулировать действия всех людей с особыми способностями, введя «Акт о регистрации супергероев», вынуждая их раскрыть свои личности и работать на правительственные службы.  Видя в этом законе нарушение гражданских прав и плевок во всё, что он верит, Стив Роджерс открыто восстаёт против нового режима, ведя за собой группу героев, поддерживающих его мнение. В свою же очередь, Тони Старк видит правильность в новом законе, и становится во главе героев, поддерживающих его. Всё это приводит к неизбежному расколу Мстителей, и гражданской войне между двумя сторонами. Сражаясь друг с другом, Старк и Роджерс не знают о том, что таинственный Барон Земо уже строит свои собственные планы, воспользовавшись расколом величайших героев Земли.",
        poster_path: "/s9htg46sXoLWfh6fBjMziWYYrpm.jpg",
        release_date: "2016-04-27",
        title: "Первый мститель: Противостояние",
        video: false,
        vote_average: 7.4,
        vote_count: 18414,
      },
      {
        adult: false,
        backdrop_path: "/a7sAqMKv5tkAdMzFfIhPqIBmQ9g.jpg",
        genre_ids: [878, 28, 12],
        id: 102899,
        media_type: "movie",
        original_language: "en",
        original_title: "Ant-Man",
        overview:
          "Вооружившись удивительной способностью уменьшаться в размере, но обладать при этом большой силой, мошенник Скотт Лэнг должен стать героем и помочь своему наставнику, доктору Хэнку Пиму, сохранить в тайне существование костюма Человека-муравья от угроз нового поколения.",
        poster_path: "/9cMJSp2LVSzmPzMWPHIHpeBfECr.jpg",
        release_date: "2015-07-14",
        title: "Человек-муравей",
        video: false,
        vote_average: 7.1,
        vote_count: 15845,
      },
    ],
    known_for_department: "Acting",
    name: "Paul Rudd",
    popularity: 20.826,
    profile_path: "/8eTtJ7XVXY0BnEeUaSiTAraTIXd.jpg",
  },
];
